### ISSUE TITLE
When there is an exception within a route's block an error occurs while trying to handle it

### ISSUE THREAD

**Issue by messuti-edd** [raggi/async_sinatra#38]
If an exception appears within the code of a route's block Im not able to see info about it because (I believe) another exception occurs while `sinatra-async` tries to send the exception to be displayed, here is the full traceback:

```
== Sinatra/1.4.5 has taken the stage on 4567 for development with backup from Thin
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on localhost:4567, CTRL+C to stop
Stopping ...
== Sinatra has ended his set (crowd applauds)
/Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call': undefined method `join' for #<String:0x007fbab19fc6a8> (NoMethodError)
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/async_sinatra-1.1.0/lib/sinatra/async.rb:169:in `rescue in async_handle_exception'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/async_sinatra-1.1.0/lib/sinatra/async.rb:165:in `async_handle_exception'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/async_sinatra-1.1.0/lib/sinatra/async.rb:155:in `async_catch_execute'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/async_sinatra-1.1.0/lib/sinatra/async.rb:124:in `block in async_schedule'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/eventmachine-1.0.7/lib/eventmachine.rb:968:in `call'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/eventmachine-1.0.7/lib/eventmachine.rb:968:in `block in run_deferred_callbacks'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/eventmachine-1.0.7/lib/eventmachine.rb:965:in `times'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/eventmachine-1.0.7/lib/eventmachine.rb:965:in `run_deferred_callbacks'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/rack-1.6.0/lib/rack/handler/thin.rb:19:in `run'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/sinatra-1.4.5/lib/sinatra/base.rb:1497:in `start_server'
	from /Users/messutiEdd/.rvm/gems/ruby-1.9.3-p362/gems/sinatra-1.4.5/lib/sinatra/base.rb:1435:in `run!'
	from app.rb:19:in `<class:AsyncTest>'
	from app.rb:3:in `<main>'
```

I'm able to reproduce this with the basic example app from the readme:
```ruby
require 'sinatra/async'

class AsyncTest < Sinatra::Base
  register Sinatra::Async

  aget '/' do
    body "hello async"
  end

  aget '/error' do
    throw "boom"
    body "hello async"
  end

  aget '/delay/:n' do |n|
    EM.add_timer(n.to_i) { body { "delayed for #{n} seconds" } }
  end

  run!
end

AsyncTest.new
```

**Comment by raggi** [comment]
Do `body ["hello async"]` and it'll stop breaking.

**Comment by messuti-edd** [comment]
That doesn't help @raggi, the error happens at `aget '/error'`, before reaching the body call, I tried what you suggest anyways and still the same problem.

**Comment by raggi** [comment]
Oh wait, this I think is a rack/sinatra incompatibility. Upgrade sinatra or downgrade rack.

**Comment by messuti-edd** [comment]
Yep that was it! thanks a bunch @raggi
